openapi: 3.0.0
info:
  title: Conversations Channel Adapter API
  version: 1.0.0
  description:
    Medallia Conversations enables communications with customers and employees
    through a conversational service such as SMS, Facebook Messenger, WhatsApp,
    and more.  A channel adapter connects Medallia Conversations with the end
    user device, handling the device-specific communications as needed.
  termsOfService: https://medallia.com/about/legal/terms/api
servers:
  - url: 'https://{conversations-api-gateway-hostname}'
    variables:
      api-gateway-hostname:
        default: conversations.sc4.medallia.com
        description:
          The Medallia Experience Cloud hostname used to access
          Medallia Conversations' API gateway.
  - url: 'https://{adapter-api-gateway-hostname}'
    variables:
      adapter-api-gateway-hostname:
        default: adapter-gateway.example.com
        description:
          The endpoint used to make requests from Medallia Conversations
          to the channel adapter.
paths:
  /:
    servers:
      - url: 'https://{adapter-api-gateway-hostname}'
        variables:
          adapter-api-gateway-hostname:
            default: adapter-gateway.example.com
            description:
              The endpoint used to make requests from Medallia
              Conversations to the channel adapter.
    post:
      tags:
        - Channel Adapter Services
      description:
        The API endpoint implemented by the Channel Adapter to accept
        messages from Medallia Conversations.
      parameters:
        - in: query
          name: access_token
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OutboundMessageRequest'
      responses:
        200:
          description: A successful response includes the customer and message IDs
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/OutboundMessageResponse'
  /{customer-id}:
    servers:
      - url: 'https://{adapter-api-gateway-hostname}'
        variables:
          adapter-api-gateway-hostname:
            default: adapter-gateway.example.com
            description:
              The endpoint used to make requests from Medallia
              Conversations to the channel adapter.
    get:
      tags:
        - Channel Adapter Services
      description:
        Returns a customer's profile data for use in Medallia
        Conversations' reporting interfaces.
      parameters:
        - in: path
          name: customer-id
          schema:
            type: string
          required: true
        - in: query
          name: access_token
          schema:
            type: string
          required: true
      responses:
        200:
          description:
            The customer's profile data.
          content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CustomerProfileData'
  /apis/v0/channels/{channel-guid}/messages:
    servers:
      - url: 'https://{conversations-api-gateway-hostname}'
        variables:
          api-gateway-hostname:
            default: conversations.sc4.medallia.com
            description:
              The Medallia Experience Cloud hostname used to access
              Medallia Conversations' API gateway.
    post:
      tags:
        - Conversations Services
      description:
        Accepts messages from the channel adapter sent to Medallia
        Conversations.  The payload is polymorphic -- that is, the shape
        of the request payload indicates whether the channel adapter is
        forwarding an inbound message from the customer, triggering a
        new conversation, or providing delivery status of the last
        sent message.
      parameters:
        - in: path
          name: channel-guid
          schema:
            type: string
          required: true
      requestBody:
        description: The request payload
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  required:
                    - query
                  properties:
                    object:
                      type: string
                      enum: [page]
                    entry:
                      type: array
                      items:
                        $ref: '#/components/schemas/ForwardedMessage'
                  additionalProperties:
                    type: string
                  example:
                    object: page
                    entry:
                      id: '6482345-345345-24525-4542'
                      time: '2021-03-23T13:15:37-07:00'
                      messaging:
                        sender:
                          id: '6482345-345345-24525-4542'
                        recipient:
                          id: '6482345-345345-24525-4542'
                        timestamp: 20493487298672
                        message:
                          mid: 6482345-345345-24525-4542, 6987364-24545-2452452-5234
                          text: Hello world!
                - type: object
                  required:
                    - query
                  properties:
                    object:
                      type: string
                      enum: [page]
                    entry:
                      type: array
                      items:
                        $ref: '#/components/schemas/ConversationTrigger'
                  additionalProperties:
                    type: string
                  example:
                    object: "page"
                    entry:
                      id: '6482345-345345-24525-4542'
                      time: '2021-03-23T13:15:37-07:00'
                      messaging:
                        sender:
                          id: '6482345-345345-24525-4542'
                        recipient:
                          id: '6482345-345345-24525-4542'
                        timestamp: 20493487298672
                        message:
                          mid: 6482345-345345-24525-4542, 6987364-24545-2452452-5234
                          text: Hello world!
                        trigger_parameters:
                          override_session: true
                          consumer:
                            id: '8069100230017427'
                            email: 'consumer1@example.com'
                          custom:
                            session_id: "e123456789-eb0d-437f-bafd-78efa6c6cce4"
                            channel: "Orion-DEV"
                            survey_type: "post-purchase-survey-prod"
                - type: object
                  required:
                    - query
                  properties:
                    object:
                      type: string
                      enum: [page]
                    entry:
                      type: array
                      items:
                        $ref: '#/components/schemas/DeliveryStatusUpdate'
                  additionalProperties:
                    type: string
                  example:
                    object: page
                    entry:
                      id: '6482345-345345-24525-4542'
                      time: '2021-03-23T13:15:37-07:00'
                      messaging:
                        sender:
                          id: '6482345-345345-24525-4542'
                        recipient:
                          id: '6482345-345345-24525-4542'
                        timestamp: 20493487298672
                        delivery:
                          mids: 6482345-345345-24525-4542, 6987364-24545-2452452-5234
                          status: delivered

      responses:
        200:
          description: The request was processed as expected
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal server error
      security:
        - conversationsOauth: []
    get:
      tags:
        - Conversations Services
      description:
        Lists all available Conversations accessible to the
        Channel Adapter.
      parameters:
        - in: query
          name: f.labels
          description: filters by the label property
          schema:
            type: string
          required: false
        - in: path
          name: channel-guid
          schema:
            type: string
          required: true
      responses:
        200:
          description:
            Returns the list of available conversations.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationsList'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        500:
          description: Internal server error
      security:
        - conversationsOauth: []
components:
  schemas:
    ConversationsList:
      properties:
        items:
          type: array
          items:
            properties:
              guid:
                type: string
                format: uuid
              title:
                type: string
              description:
                type: string
              keyword:
                type: array
                items:
                    type: string
              labels:
                type: array
                items:
                    type: string
              created_at:
                type: string
                format: date-time
                description: CV: IN WHAT FORMAT?
              updated_at:
                type: string
                format: date-time
                description: CV: IN WHAT FORMAT?
        _total:
          type: integer
          format: int64
    CustomerProfileData:
      properties:
        first_name:
          type: string
        last_name:
          type: string
        profile_pic:
          type: string
          description: CV: IN WHAT FORMAT?
        locale:
          type: string
          description: CV: IN WHAT FORMAT?
        timezone:
          type: string
          description: CV: IN WHAT FORMAT?
        phone_number:
          type: string
          description: CV: IN WHAT FORMAT?
    OutboundMessageRequest:
      properties:
        recipient:
          properties:
            id:
              type: string
              description:
                An identifier unique to the customer, such as phone number,
                email, or another channel-specific value. For phone numbers,
                the identifier must be in E.164 format.
        message:
          properties:
            text:
              type: string
            quick_replies:
              type: array
              items:
                properties:
                  content_type:
                    type: string
                  title:
                    type: string
                  payload:
                    type: string
                  image_url:
                    type: string
                    format: uri
            notification_type:
              type: string
              enum: [REGULAR]
    OutboundMessageResponse:
      properties:
        recipient_id:
          type: string
          description:
            The identifier for the recipient, as sent in the original
            request.
        message_id:
          type: string
          description:
            A unique identifier for the message, assigned by the
            channel adapter.
    ForwardedMessage:
      properties:
        id:
          type: string
          description:
            CV - THIS NEEDS TO BE UPDATED.  It's unclear what ID
            (channel guid, page id, etc.) it refers to.

            The unique identifier — in Medallia Conversations — of the
            messaging application instance. A different instance on the
            adapter must have another Page ID.
        time:
          type: integer
          format: int64
          description:
            Unix epoch timestamp of the last event associated with the
            request. For example, when it is a multi-part message, this
            is the time of the last message-part.
        messaging:
          type: array
          items:
            properties:
              sender:
                properties:
                  id:
                    type: string
                    description:
                      An identifier unique to the customer, such as phone
                      number, email, or other channel-specific value.
                      For phone numbers, the ID must be in E.164 format.
              recipient:
                properties:
                  id:
                    type: string
                    description:
                      CV - THIS NEEDS TO BE UPDATED.  It's unclear what ID
                      (channel guid, page id, etc.) it refers to.

                      Unique identifier in Medallia Conversations of the
                      messaging application instance. A different instance
                      on the adapter must have another Page ID.
              timestamp:
                type: integer
                format: int64
                description:
                  Unix epoch timestamp of the last event associated with the
                  request. For example, when it is a multi-part message, this
                  is the time of the last message-part.
              message:
                properties:
                  mid:
                    type: string
                  text:
                    type: string
                    description:
                      The message text, no longer than 1,600 characters.
                      The channel service may split the message into
                      multiple parts for delivery.
    ConversationTrigger:
      properties:
        id:
          type: string
          description:
            Unique identifier — in Medallia Conversations — of the
            messaging application instance. A different instance on the
            adapter must have another Page ID.
        time:
          type: integer
          format: int64
          description:
            Unix epoch timestamp of the last event associated with the
            request. For example, when it is a multi-part message, this
            is the time of the last message-part.
        messaging:
          type: array
          items:
            properties:
              sender:
                properties:
                  id:
                    type: string
                    description:
                      An identifier unique to the customer, such as phone
                      number, email, or other channel-specific value.
                      For phone numbers, the ID must be in E.164 format.
              recipient:
                properties:
                  id:
                    type: string
                    description:
                      CV - THIS NEEDS TO BE UPDATED.  It's unclear what ID
                      (channel guid, page id, etc.) it refers to.

                      Unique identifier in Medallia Conversations of the
                      messaging application instance. A different instance
                      on the adapter must have another Page ID.
              timestamp:
                type: integer
                format: int64
              message:
                properties:
                  mid:
                    type: string
                  text:
                    type: string
                    description:
                      The message text, no longer than 1,600 characters.
                      The channel service may split the message into
                      multiple parts for delivery.
              trigger_parameters:
                properties:
                  override_session:
                    type: boolean
                  consumer:
                    properties:
                      id:
                        type: string
                      email:
                        type: string
                  custom:
                    description:
                      A dictionary with the custom parameters, mapped
                      to fields in Medallia Reporting via survey
                      parameters.
                    properties:
                      session_id:
                        type: string
                      channel:
                        type: string
                      survey_type:
                        type: string
                      queue:
                        type: string
                      e_unitid:
                        type: string
    DeliveryStatusUpdate:
      properties:
        id:
          type: string
          description:
            CV - THIS NEEDS TO BE UPDATED.  It's unclear what ID
            (channel guid, page id, etc.) it refers to.

            Unique identifier — in Medallia Conversations — of the
            messaging application instance. A different instance on
            the adapter must have another Page ID.
        time:
          type: integer
          format: int64
          description:
            Unix epoch timestamp of the last event associated with
            the request. For example, when it is a multi-part message,
            this is the time of the last message-part.
        messaging:
          type: array
          items:
            properties:
              sender:
                properties:
                  id:
                    type: string
                    description:
                      An identifier unique to the customer, such as
                      phone number, email, or other channel-specific
                      value. For phone numbers, the ID must be in
                      E.164 format.
              recipient:
                properties:
                  id:
                    type: string
                    description:
                      CV - THIS NEEDS TO BE UPDATED.  It's unclear what ID
                      (channel guid, page id, etc.) it refers to.

                      Unique identifier — in Medallia Conversations — of the
                      messaging application instance. A different instance on
                      the adapter must have another Page ID.
              timestamp:
                type: integer
                format: int64
              delivery:
                properties:
                  mids:
                    type: array
                    items:
                      type: string
                    description:
                      (required) Identifier for the messages sent as
                      generated by the channel service. Used for tracking
                      and debugging.
                  status:
                    type: string
                  error:
                    properties:
                      code:
                        type: string
                        enum: [ failed, sent, delivered, undelivered ]
                      name:
                        type: string
                      message:
                        type: string
  securitySchemes:
    conversationsOauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://{conversations-api-gateway-hostname}/oauth/{company}/token
          scopes: {}
